invalid-syntax: Simple statements must be separated by newlines or semicolons   --> file3.py:36:7    | 34 | scratch_dir = os.environ.get('VSC_SCRATCH') 35 | filename_p1 = scratch_dir + "/primes_1.txt" 36 | print "Output File: ", filename_p1    |       ^^^^^^^^^^^^^^^ 37 | f_out = open(filename_p1, 'w+') 38 | for i in range(1, 30000):    |
invalid-syntax: Simple statements must be separated by newlines or semicolons
  --> file3.py:59:7
   |
57 | f_in=open(filename_p1, "r")
58 | f_out=open(filename_p2, "w")
59 | print "Input File: ", filename_p1
   |       ^^^^^^^^^^^^^^
60 | print "Output File: ", filename_p2
61 | in_lines=f_in.readlines()                                #reads it line by line
   |

invalid-syntax: Simple statements must be separated by newlines or semicolons
  --> file3.py:60:7
   |
58 | f_out=open(filename_p2, "w")
59 | print "Input File: ", filename_p1
60 | print "Output File: ", filename_p2
   |       ^^^^^^^^^^^^^^^
61 | in_lines=f_in.readlines()                                #reads it line by line
62 | for line in in_lines:
   |

invalid-syntax: Simple statements must be separated by newlines or semicolons
  --> file3.py:81:7
   |
79 | end_time = int(time.time())
80 | duration = end_time - start_time
81 | print "Duration = " + str(duration) + " seconds."
   |       ^^^^^^^^^^^^^
   |

Found 4 errors.

error: Failed to parse file3.py:36:7: Simple statements must be separated by newlines or semicolons
F401 [*] `sys` imported but unused
  --> file3.py:10:8
   |
 8 | """
 9 |
10 | import sys
   |        ^^^
11 | import random
12 | import datetime
   |
help: Remove unused import: `sys`

F401 [*] `datetime` imported but unused
  --> file3.py:12:8
   |
10 | import sys
11 | import random
12 | import datetime
   |        ^^^^^^^^
13 | import time
14 | import os
   |
help: Remove unused import: `datetime`

Found 2 errors.
[*] 2 fixable with the `--fix` option.
************* Module file3
file3.py:7:0: C0301: Line too long (112/100) (line-too-long)
file3.py:71:0: W0311: Bad indentation. Found 1 spaces, expected 4 (bad-indentation)
file3.py:72:0: W0311: Bad indentation. Found 1 spaces, expected 4 (bad-indentation)
file3.py:73:0: W0311: Bad indentation. Found 1 spaces, expected 4 (bad-indentation)
file3.py:74:0: W0311: Bad indentation. Found 1 spaces, expected 4 (bad-indentation)
file3.py:75:0: W0311: Bad indentation. Found 1 spaces, expected 4 (bad-indentation)
file3.py:76:0: W0311: Bad indentation. Found 1 spaces, expected 4 (bad-indentation)
file3.py:77:0: W0311: Bad indentation. Found 1 spaces, expected 4 (bad-indentation)
file3.py:78:0: W0311: Bad indentation. Found 2 spaces, expected 8 (bad-indentation)
file3.py:79:0: W0311: Bad indentation. Found 1 spaces, expected 4 (bad-indentation)
file3.py:80:0: W0311: Bad indentation. Found 1 spaces, expected 4 (bad-indentation)
file3.py:81:0: W0311: Bad indentation. Found 1 spaces, expected 4 (bad-indentation)
file3.py:82:0: W0311: Bad indentation. Found 1 spaces, expected 4 (bad-indentation)
file3.py:83:0: W0311: Bad indentation. Found 1 spaces, expected 4 (bad-indentation)
file3.py:63:5: W1514: Using open without explicitly specifying an encoding (unspecified-encoding)
file3.py:64:6: W1514: Using open without explicitly specifying an encoding (unspecified-encoding)
file3.py:75:1: C0103: Constant name "tot" doesn't conform to UPPER_CASE naming style (invalid-name)
file3.py:63:5: R1732: Consider using 'with' for resource-allocating operations (consider-using-with)
file3.py:64:6: R1732: Consider using 'with' for resource-allocating operations (consider-using-with)

------------------------------------------------------------------
Your code has been rated at 6.20/10 (previous run: 6.20/10, +0.00)

$ python3.14  file3.py
Output File: ./primes_1.txt
Traceback (most recent call last):
  File "/tmp/brol/file3.py", line 64, in <module>
    filename_p1 = scratch_dir + "/primes_1.txt"
                  ~~~~~~~~~~~~^~~~~~~~~~~~~~~~~
TypeError: unsupported operand type(s) for +: 'NoneType' and 'str'

$ python3.14  file3.py
Output File: ./primes_1.txt
Input File: ./primes_1.txt
Output File: ./primes_2.txt
Traceback (most recent call last):
  File "/tmp/brol/file3.py", line 88, in <module>
    tot += int(list_values[i])
           ~~~^^^^^^^^^^^^^^^^
ValueError: invalid literal for int() with base 10: ''