fix python code in fibo.py
$ python fibo.py
  File "/tmp/brol/fibo.py", line 8
                print b,
                ^^^^^^^^
SyntaxError: Missing parentheses in call to 'print'. Did you mean print(...)?

 ruff check  fibo.py
invalid-syntax: Simple statements must be separated by newlines or semicolons
 --> fibo.py:8:9
  |
6 |     a, b = 0, 1
7 |     while b < n:
8 |         print b,
  |               ^
9 |         a, b = b, a+b
  |

Found 1 error.

(brol) user@computer:/tmp/brol$ ruff check  fibo.py
All checks passed!
(brol) user@computer:/tmp/brol$ pylint  fibo.py
************* Module fibo
fibo.py:6:0: W0311: Bad indentation. Found 1 spaces, expected 4 (bad-indentation)
fibo.py:7:0: W0311: Bad indentation. Found 1 spaces, expected 4 (bad-indentation)
fibo.py:8:0: W0311: Bad indentation. Found 2 spaces, expected 8 (bad-indentation)
fibo.py:9:0: W0311: Bad indentation. Found 2 spaces, expected 8 (bad-indentation)
fibo.py:12:0: W0311: Bad indentation. Found 1 spaces, expected 4 (bad-indentation)
fibo.py:13:0: W0311: Bad indentation. Found 1 spaces, expected 4 (bad-indentation)
fibo.py:14:0: W0311: Bad indentation. Found 1 spaces, expected 4 (bad-indentation)
fibo.py:15:0: W0311: Bad indentation. Found 2 spaces, expected 8 (bad-indentation)
fibo.py:16:0: W0311: Bad indentation. Found 2 spaces, expected 8 (bad-indentation)
fibo.py:17:0: W0311: Bad indentation. Found 1 spaces, expected 4 (bad-indentation)
fibo.py:20:0: W0311: Bad indentation. Found 1 spaces, expected 4 (bad-indentation)
fibo.py:1:0: C0114: Missing module docstring (missing-module-docstring)
fibo.py:5:0: C0116: Missing function or method docstring (missing-function-docstring)
fibo.py:8:2: W0106: Expression "(print(b), )" is assigned to nothing (expression-not-assigned)
fibo.py:11:0: C0116: Missing function or method docstring (missing-function-docstring)

-----------------------------------
Your code has been rated at 0.00/10

(brol)  20 user@computer:/tmp/brol$ vi fibo.commit
(brol) user@computer:/tmp/brol$ ruff check --fix fibo.py
All checks passed!
(brol) user@computer:/tmp/brol$ ruff format fibo.py
1 file reformatted
(brol) user@computer:/tmp/brol$ pylint  fibo.py
************* Module fibo
fibo.py:1:0: C0114: Missing module docstring (missing-module-docstring)
fibo.py:6:0: C0116: Missing function or method docstring (missing-function-docstring)
fibo.py:9:8: W0106: Expression "(print(b), )" is assigned to nothing (expression-not-assigned)
fibo.py:13:0: C0116: Missing function or method docstring (missing-function-docstring)

------------------------------------------------------------------
Your code has been rated at 7.33/10 (previous run: 0.00/10, +7.33)