fix python code in message.py
 python message.py
/tmp/brol/message.py:19: SyntaxWarning: invalid escape sequence '\ '
  \   ^__^ \n\
  File "/tmp/brol/message.py", line 25
        print cowtxt
        ^^^^^^^^^^^^
SyntaxError: Missing parentheses in call to 'print'. Did you mean print(...)?

$ ruff format message.py
error: Failed to parse message.py:25:8: Simple statements must be separated by newlines or semicolons

$ pylint
************* Module message
mkdocs/docs/HPC/examples/Running_interactive_jobs/message.py:25:2: E0001: Parsing failed: 'Missing parentheses in call to 'print'. Did you mean print(...)? (<unknown>, line 25)' (syntax-error)

************* Module message
message.py:14:0: W0311: Bad indentation. Found 1 spaces, expected 4 (bad-indentation)
message.py:15:0: W0311: Bad indentation. Found 1 spaces, expected 4 (bad-indentation)
message.py:16:0: W0311: Bad indentation. Found 1 spaces, expected 4 (bad-indentation)
message.py:17:0: W0311: Bad indentation. Found 1 spaces, expected 4 (bad-indentation)
message.py:18:0: W0311: Bad indentation. Found 1 spaces, expected 4 (bad-indentation)
message.py:19:0: W0311: Bad indentation. Found 1 spaces, expected 4 (bad-indentation)
message.py:28:0: W0311: Bad indentation. Found 1 spaces, expected 4 (bad-indentation)
message.py:34:0: W0311: Bad indentation. Found 2 spaces, expected 4 (bad-indentation)
message.py:36:0: W0311: Bad indentation. Found 2 spaces, expected 4 (bad-indentation)
message.py:22:11: W1401: Anomalous backslash in string: '\ '. String constant might be missing an r prefix. (anomalous-backslash-in-string)
message.py:23:11: W1401: Anomalous backslash in string: '\ '. String constant might be missing an r prefix. (anomalous-backslash-in-string)
message.py:23:18: W1401: Anomalous backslash in string: '\_'. String constant might be missing an r prefix. (anomalous-backslash-in-string)
message.py:24:18: W1401: Anomalous backslash in string: '\ '. String constant might be missing an r prefix. (anomalous-backslash-in-string)
message.py:24:27: W1401: Anomalous backslash in string: '\/'. String constant might be missing an r prefix. (anomalous-backslash-in-string)
message.py:24:29: W1401: Anomalous backslash in string: '\ '. String constant might be missing an r prefix. (anomalous-backslash-in-string)
message.py:13:0: C0116: Missing function or method docstring (missing-function-docstring)
message.py:31:0: C0103: Constant name "cmd" doesn't conform to UPPER_CASE naming style (invalid-name)
message.py:32:0: C0103: Constant name "ret" doesn't conform to UPPER_CASE naming style (invalid-name)
message.py:11:0: W0611: Unused import sys (unused-import)

------------------------------------------------------------------
Your code has been rated at 0.00/10 (previous run: 0.00/10, +0.00)

F401 [*] `sys` imported but unused
  --> message.py:11:8
   |
10 | import subprocess
11 | import sys
   |        ^^^
12 |
13 | def print_cowsay(cowsay):
   |
help: Remove unused import: `sys`

Found 1 error.
[*] 1 fixable with the `--fix` option.